--
-- Описание для таблицы ALIASES
--
CREATE TABLE ALIASES (
  ALIASES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ALIASES_ID),
  INDEX idx_ALIASES_1 (ITEM_ID),
  INDEX idx_ALIASES_2 (BRAND_ID, NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;
