--
-- Описание для таблицы ALIGN
--
CREATE TABLE ALIGN (
  ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 23
AVG_ROW_LENGTH = 42
CHARACTER SET utf8
COLLATE utf8_general_ci;
