--
-- Описание для таблицы ANNOUNCEMENTS
--
CREATE TABLE ANNOUNCEMENTS (
  ANN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  FIO varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  PRICE varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  PHONE varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  POSTED_AT datetime DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ANN_ID),
  INDEX idx_ANNOUNCEMENTS_1 (BRAND_ID, ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;
