--
-- Описание для таблицы ANOTHER_PAGES
--
CREATE TABLE ANOTHER_PAGES (
  ANOTHER_PAGES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  REALCATNAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  TEMPLATE varchar(255) DEFAULT NULL,
  TITLE text DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  KEYWORDS text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  IS_NEW_WIN int(1) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDER_ int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ANOTHER_PAGES_ID),
  INDEX idx_ANOTHER_PAGES_1 (PARENT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 61
AVG_ROW_LENGTH = 253
CHARACTER SET utf8
COLLATE utf8_general_ci;
