--
-- Описание для таблицы ARTICLE_GROUP
--
CREATE TABLE ARTICLE_GROUP (
  ARTICLE_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ARTICLE_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;
