--
-- Описание для таблицы ATTR_CATALOG_VIS
--
CREATE TABLE ATTR_CATALOG_VIS (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CATALOGUE_ID, ATTRIBUT_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;
