--
-- Описание для таблицы ATTRIBUT
--
CREATE TABLE ATTRIBUT (
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  ID_FROM_VBD int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  TITLE text DEFAULT NULL,
  ICON_IMAGE varchar(50) DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  UNIT_ID int(12) UNSIGNED DEFAULT NULL,
  VIEW_ATTRIBUT_GROUP_ID int(12) UNSIGNED NOT NULL,
  ALTER_VALUE varchar(255) DEFAULT NULL,
  SHOW_ int(1) UNSIGNED DEFAULT NULL,
  SHOW_RIGHT int(1) UNSIGNED DEFAULT NULL,
  IS_LINK int(1) UNSIGNED DEFAULT NULL,
  IS_RANGEABLE int(1) UNSIGNED DEFAULT NULL,
  IS_RANGE_VIEW tinyint(1) UNSIGNED DEFAULT NULL,
  IS_CHOISE int(1) UNSIGNED DEFAULT NULL,
  NOT_CARD int(1) NOT NULL DEFAULT 0,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  MULTIPLE_ int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD)
)
ENGINE = MYISAM
AUTO_INCREMENT = 6280
AVG_ROW_LENGTH = 75
CHARACTER SET utf8
COLLATE utf8_general_ci;
