--
-- Описание для таблицы ATTR_CATALOG_LINK
--
CREATE TABLE ATTR_CATALOG_LINK (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  IN_PODBOR int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID, ATTRIBUT_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 13
CHARACTER SET utf8
COLLATE utf8_general_ci;
