--
-- Описание для таблицы BANN_SECTION
--
CREATE TABLE BANN_SECTION (
  BANN_SECTION_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (BANN_SECTION_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 21
AVG_ROW_LENGTH = 44
CHARACTER SET utf8
COLLATE utf8_general_ci;
