--
-- Описание для таблицы BRAND
--
CREATE TABLE BRAND (
  BRAND_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  IMAGE varchar(255) NOT NULL,
  TITLE varchar(255) DEFAULT NULL,
  SUBTITLE varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  ALT_NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IN_INDEX int(1) UNSIGNED NOT NULL,
  IN_ALL_PAGES int(1) UNSIGNED NOT NULL,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (BRAND_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD),
  INDEX idx_BRAND_1 (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 13867150
AVG_ROW_LENGTH = 53
CHARACTER SET utf8
COLLATE utf8_general_ci;
