--
-- Описание для таблицы CALLBACK
--
CREATE TABLE CALLBACK (
  CALLBACK_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PHONE varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CALLBACK_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 615
AVG_ROW_LENGTH = 819
CHARACTER SET utf8
COLLATE utf8_general_ci;
