--
-- Описание для таблицы CAT_HOME_TYPE
--
CREATE TABLE CAT_HOME_TYPE (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  HOME_TYPE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CATALOGUE_ID, HOME_TYPE_ID),
  INDEX idx_CAT_HOME_TYPE_1 (HOME_TYPE_ID)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci;
