--
-- Описание для таблицы CAT_BRAND
--
CREATE TABLE CAT_BRAND (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  BRAND_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID, BRAND_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 13
CHARACTER SET utf8
COLLATE utf8_general_ci;
