--
-- Описание для таблицы CATALOGUE_SECTION_ALIGN
--
CREATE TABLE CATALOGUE_SECTION_ALIGN (
  CATALOGUE_SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_SECTION_ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 151
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
