--
-- Описание для таблицы CATALOGUE_PRICE_EXPORT
--
CREATE TABLE CATALOGUE_PRICE_EXPORT (
  CATALOGUE_PRICE_EXPORT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  PRICE_EXPORT_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_PRICE_EXPORT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 530
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
