--
-- Описание для таблицы CATALOGUE_BRAND_VIEW
--
CREATE TABLE CATALOGUE_BRAND_VIEW (
  CATALOGUE_BRAND_VIEW_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_BRAND_VIEW_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 538
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
