--
-- Описание для таблицы CATALOGUE
--
CREATE TABLE CATALOGUE (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(12) UNSIGNED NOT NULL,
  PARENT_ID int(12) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  NAME_ALTER varchar(255) DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  REALCATNAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  SUB_ITEM_TITLE varchar(255) NOT NULL DEFAULT '',
  SUB_TITLE varchar(255) NOT NULL DEFAULT '',
  DESC_META text DEFAULT NULL,
  KEYWORD_META text DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  SEO_LEFT text DEFAULT NULL,
  SEO_RIGHT text DEFAULT NULL,
  SEO_BOTTOM text DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  IN_ADV int(1) UNSIGNED NOT NULL,
  IS_INDEX tinyint(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD),
  INDEX idx_CATALOGUE_1 (PARENT_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 281
AVG_ROW_LENGTH = 1086
CHARACTER SET utf8
COLLATE utf8_general_ci;
