--
-- Описание для таблицы CMF_USER
--
CREATE TABLE CMF_USER (
  CMF_USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  MD5_ varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  LOGIN varchar(255) DEFAULT NULL,
  PASS_ varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_USER_ID),
  INDEX idx_CMF_USER_1 (MD5_),
  INDEX idx_CMF_USER_2 (LOGIN)
)
ENGINE = MYISAM
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 91
CHARACTER SET utf8
COLLATE utf8_general_ci;
