--
-- Описание для таблицы CMF_SCRIPT_GROUP
--
CREATE TABLE CMF_SCRIPT_GROUP (
  CMF_SCRIPT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  R int(1) UNSIGNED DEFAULT NULL,
  W int(1) UNSIGNED DEFAULT NULL,
  D int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_SCRIPT_ID, CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 163
AVG_ROW_LENGTH = 21
CHARACTER SET utf8
COLLATE utf8_general_ci;
