--
-- Описание для таблицы CMF_USER_GROUP
--
CREATE TABLE CMF_USER_GROUP (
  CMF_USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CMF_USER_ID, CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;
