--
-- Описание для таблицы CMF_SCRIPT
--
CREATE TABLE CMF_SCRIPT (
  CMF_SCRIPT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  ARTICLE varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  BACKGROUND varchar(255) DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_SCRIPT_ID),
  INDEX idx_CMF_SCRIPT_1 (PARENT_ID),
  INDEX idx_CMF_SCRIPT_2 (ARTICLE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 163
AVG_ROW_LENGTH = 85
CHARACTER SET utf8
COLLATE utf8_general_ci;
