--
-- Описание для таблицы CMF_GROUP
--
CREATE TABLE CMF_GROUP (
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  PRIMARY KEY (CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 52
CHARACTER SET utf8
COLLATE utf8_general_ci;
