--
-- Описание для таблицы CMF_LANG
--
CREATE TABLE CMF_LANG (
  CMF_LANG_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYSTEM_NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_LANG_ID),
  UNIQUE INDEX idx_CMF_LANG_1 (SYSTEM_NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 28
CHARACTER SET utf8
COLLATE utf8_general_ci;
