--
-- Описание для таблицы CMF_XMLS_ARTICLE
--
CREATE TABLE CMF_XMLS_ARTICLE (
  TYPE int(12) UNSIGNED NOT NULL DEFAULT 0,
  ARTICLE varchar(255) DEFAULT NULL,
  EDIT varchar(255) DEFAULT NULL,
  VIEW varchar(255) DEFAULT NULL,
  PRIMARY KEY (TYPE)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 58
CHARACTER SET utf8
COLLATE utf8_general_ci;
