--
-- Описание для таблицы DELIVERY
--
CREATE TABLE DELIVERY (
  DELIVERY_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD varchar(5) NOT NULL DEFAULT '0',
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  LONG_TEXT text NOT NULL,
  PRIMARY KEY (DELIVERY_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 1468
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
