--
-- Описание для таблицы DISCOUNTS
--
CREATE TABLE DISCOUNTS (
  DISCOUNT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  IMAGE1 varchar(255) NOT NULL DEFAULT '',
  ORDERING tinyint(4) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (DISCOUNT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 13
AVG_ROW_LENGTH = 64
CHARACTER SET utf8
COLLATE utf8_general_ci;
