--
-- Описание для таблицы GOODS_GROUP_ITEM_LINK
--
CREATE TABLE GOODS_GROUP_ITEM_LINK (
  GOODS_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  BASE_IMAGE varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  INDEX idx_GOODS_GROUP_ITEM_LINK_1 (GOODS_GROUP_ID),
  INDEX idx_GOODS_GROUP_ITEM_LINK_2 (ITEM_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;
