--
-- Описание для таблицы ITEM_MEDIA
--
CREATE TABLE ITEM_MEDIA (
  ITEM_MEDIA_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  MEDIA_FILE varchar(50) DEFAULT NULL,
  MEDIA_CODE text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ITEM_MEDIA_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 150
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
