--
-- Описание для таблицы ITEMR
--
CREATE TABLE ITEMR (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  RANGE_LIST_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEMR_1 (ATTRIBUT_ID, RANGE_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;
