--
-- Описание для таблицы ITEM_PHOTO
--
CREATE TABLE ITEM_PHOTO (
  ITEM_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  IMAGE2 varchar(50) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 10269
AVG_ROW_LENGTH = 78
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
