--
-- Описание для таблицы ITEM_DEL
--
CREATE TABLE ITEM_DEL (
  ITEM_REAL int(11) NOT NULL DEFAULT 0,
  ARTICLE_REAL varchar(255) DEFAULT NULL,
  ITEM_DELETE int(11) DEFAULT NULL,
  PRIMARY KEY (ITEM_REAL),
  UNIQUE INDEX ARTICLE_REAL (ARTICLE_REAL)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 268
CHARACTER SET utf8
COLLATE utf8_general_ci;
