--
-- Описание для таблицы ITEM_OLD
--
CREATE TABLE ITEM_OLD (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  DISCOUNT_ID int(12) UNSIGNED DEFAULT NULL,
  WARRANTY_ID int(12) UNSIGNED NOT NULL,
  DELIVERY_ID int(12) UNSIGNED NOT NULL,
  CREDIT_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  ARTICLE varchar(255) DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRICE double DEFAULT NULL,
  PRICE1 double DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  PURCHASE_PRICE double NOT NULL,
  IMAGE2 varchar(50) DEFAULT NULL,
  IMAGE3 varchar(50) DEFAULT NULL,
  NEED_RESIZE int(1) UNSIGNED NOT NULL,
  BASE_IMAGE varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  SEO_BOTTOM text DEFAULT NULL,
  YANDEX_XML int(1) UNSIGNED DEFAULT NULL,
  TITLE varchar(255) NOT NULL,
  DESC_META text NOT NULL,
  KEYWORD_META text NOT NULL,
  DATE_INSERT date DEFAULT NULL,
  IS_ACTION tinyint(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID),
  INDEX idx_ITEM_1 (CATALOGUE_ID),
  INDEX idx_ITEM_2 (BRAND_ID),
  INDEX idx_ITEM_3 (ARTICLE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16505
AVG_ROW_LENGTH = 150
CHARACTER SET utf8
COLLATE utf8_general_ci;
