--
-- Описание для таблицы ITEM_REQUEST
--
CREATE TABLE ITEM_REQUEST (
  ITEM_REQUEST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_REQUEST_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 49
AVG_ROW_LENGTH = 341
CHARACTER SET utf8
COLLATE utf8_general_ci;
