--
-- Описание для таблицы ITEM1
--
CREATE TABLE ITEM1 (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE double DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEM1_1 (ATTRIBUT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;
