--
-- Описание для таблицы NEWS_GROUP
--
CREATE TABLE NEWS_GROUP (
  NEWS_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (NEWS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 29
CHARACTER SET utf8
COLLATE utf8_general_ci;
