--
-- Описание для таблицы NEWS
--
CREATE TABLE NEWS (
  NEWS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NEWS_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE1 varchar(255) NOT NULL DEFAULT '',
  URL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (NEWS_ID),
  INDEX idx_NEWS_1 (DATA),
  INDEX idx_NEWS_2 (NEWS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 190
AVG_ROW_LENGTH = 364
CHARACTER SET utf8
COLLATE utf8_general_ci;
