--
-- Описание для таблицы OLD_SEF_URL
--
CREATE TABLE OLD_SEF_URL (
  OLD_SEF_URL_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SEF_SITE_URL_ID int(12) UNSIGNED DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  PRIMARY KEY (OLD_SEF_URL_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1061
AVG_ROW_LENGTH = 52
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
