--
-- Описание для таблицы PRICE_EXPORT
--
CREATE TABLE PRICE_EXPORT (
  PRICE_EXPORT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  INDENT varchar(255) DEFAULT NULL,
  PRIMARY KEY (PRICE_EXPORT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 27
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
