--
-- Описание для таблицы RANGE_LIST
--
CREATE TABLE RANGE_LIST (
  RANGE_LIST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  MIN double DEFAULT NULL,
  MAX double DEFAULT NULL,
  COMMENT_ text DEFAULT NULL,
  ICON varchar(50) DEFAULT NULL,
  ICON2 varchar(50) DEFAULT NULL,
  SHOW_ int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_ID, RANGE_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 46
CHARACTER SET utf8
COLLATE utf8_general_ci;
