--
-- Описание для таблицы REDIRECTOR
--
CREATE TABLE REDIRECTOR (
  REDIRECTOR_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  URL_FROM varchar(255) DEFAULT NULL,
  URL_TO varchar(255) DEFAULT NULL,
  PRIMARY KEY (REDIRECTOR_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 72
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
