--
-- Описание для таблицы RESPONSES
--
CREATE TABLE RESPONSES (
  RESPONSES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  HIDE int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (RESPONSES_ID),
  INDEX idx_RESPONSES_1 (ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 809
AVG_ROW_LENGTH = 367
CHARACTER SET utf8
COLLATE utf8_general_ci;
