--
-- Описание для таблицы SECTION_ALIGN
--
CREATE TABLE SECTION_ALIGN (
  BANN_SECTION_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ALIGN_ID int(12) UNSIGNED DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  ALT varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  BANNER_CODE text DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  NEWWIN int(1) UNSIGNED DEFAULT NULL,
  IS_ADV int(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED NOT NULL,
  PRIMARY KEY (BANN_SECTION_ID, SECTION_ALIGN_ID),
  INDEX idx_SECTION_ALIGN_1 (ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 276
CHARACTER SET utf8
COLLATE utf8_general_ci;
