--
-- Описание для таблицы SEF_SITE_URL
--
CREATE TABLE SEF_SITE_URL (
  SEF_SITE_URL_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SEF_URL varchar(255) DEFAULT NULL,
  SITE_URL varchar(255) DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  PRIMARY KEY (SEF_SITE_URL_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2030
AVG_ROW_LENGTH = 93
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
