--
-- Описание для таблицы SEQUENCES
--
CREATE TABLE SEQUENCES (
  SEQUENCES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SEQUENCES_ID),
  UNIQUE INDEX idx_SEQUENCES_1 (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 77
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;
