--
-- Описание для таблицы SETINGS
--
CREATE TABLE SETINGS (
  SETINGS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYSTEM_NAME varchar(255) DEFAULT NULL,
  VALUE text DEFAULT NULL,
  PRIMARY KEY (SETINGS_ID),
  UNIQUE INDEX idx_SETINGS_1 (SYSTEM_NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 48
AVG_ROW_LENGTH = 138
CHARACTER SET utf8
COLLATE utf8_general_ci;
