--
-- Описание для таблицы SHOPUSER
--
CREATE TABLE SHOPUSER (
  USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SHOPUSER_DISCOUNTS_ID int(12) UNSIGNED NOT NULL,
  IS_NEW int(1) UNSIGNED DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  SURNAME varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  BONUS text NOT NULL,
  REGDATA datetime DEFAULT NULL,
  PRIVATEINFO text DEFAULT NULL,
  TELMOB varchar(255) DEFAULT NULL,
  TELMOBT1 varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  UNIQUE INDEX UK_SHOPUSER_EMAIL (EMAIL)
)
ENGINE = MYISAM
AUTO_INCREMENT = 945
AVG_ROW_LENGTH = 185
CHARACTER SET utf8
COLLATE utf8_general_ci;
