--
-- Описание для таблицы SHOPUSER_SUBSCRIBE_CLIENT_GROUP
--
CREATE TABLE SHOPUSER_SUBSCRIBE_CLIENT_GROUP (
  SHOPUSER_SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED NOT NULL,
  USER_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SHOPUSER_SUBSCRIBE_CLIENT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
