--
-- Описание для таблицы SHOPUSER_DISCOUNTS
--
CREATE TABLE SHOPUSER_DISCOUNTS (
  SHOPUSER_DISCOUNTS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  CLASS_NAME varchar(255) DEFAULT NULL,
  MIN double NOT NULL,
  MAX double NOT NULL,
  IMAGE1 varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  IMAGE2 varchar(255) DEFAULT NULL,
  COLOR varchar(20) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SHOPUSER_DISCOUNTS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 109
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
