--
-- Описание для таблицы SOCIALS
--
CREATE TABLE SOCIALS (
  SOCIALS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME text DEFAULT NULL,
  INDENT varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SOCIALS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 109
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
