--
-- Описание для таблицы TEXTES
--
CREATE TABLE TEXTES (
  TEXTES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYS_NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  PRIMARY KEY (TEXTES_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci;
