--
-- Описание для таблицы UNIT
--
CREATE TABLE UNIT (
  UNIT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (UNIT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 92
AVG_ROW_LENGTH = 21
CHARACTER SET utf8
COLLATE utf8_general_ci;
