--
-- Описание для таблицы VIEW_ATTRIBUT_GROUP
--
CREATE TABLE VIEW_ATTRIBUT_GROUP (
  VIEW_ATTRIBUT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (VIEW_ATTRIBUT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 299
AVG_ROW_LENGTH = 29
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
