--
-- Описание для таблицы WARRANTY
--
CREATE TABLE WARRANTY (
  WARRANTY_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(1) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  LONG_TEXT text NOT NULL,
  PRIMARY KEY (WARRANTY_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 1650
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;
