--
-- Описание для таблицы XMLS
--
CREATE TABLE XMLS (
  XMLS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  TYPE int(12) UNSIGNED NOT NULL DEFAULT 0,
  XML text DEFAULT NULL,
  PRIMARY KEY (XMLS_ID, TYPE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 20294
AVG_ROW_LENGTH = 3224
CHARACTER SET utf8
COLLATE utf8_general_ci;
