--
-- Описание для таблицы ZAKAZ_ITEM_OLD
--
CREATE TABLE ZAKAZ_ITEM_OLD (
  ZAKAZ_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ZAKAZ_ID int(12) UNSIGNED NOT NULL,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRICE double DEFAULT NULL,
  ITEM_PRICE double DEFAULT NULL,
  ITEM_CURRENCY varchar(10) DEFAULT NULL,
  PURCHASE_PRICE double DEFAULT NULL,
  QUANTITY double DEFAULT NULL,
  COST double DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ITEM_ID),
  INDEX CURRENCY_ID (CURRENCY_ID),
  INDEX ITEM_ID (ITEM_ID),
  INDEX ZAKAZ_ID (ZAKAZ_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 6073
AVG_ROW_LENGTH = 100
CHARACTER SET utf8
COLLATE utf8_general_ci;
