--
-- Описание для таблицы ZAKAZSTATUS
--
CREATE TABLE ZAKAZSTATUS (
  ZAKAZSTATUS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  COLOR varchar(20) NOT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZSTATUS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 37
CHARACTER SET utf8
COLLATE utf8_general_ci;
