--
-- Описание для таблицы ZAKAZ_ITEM
--
CREATE TABLE ZAKAZ_ITEM (
  ZAKAZ_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ZAKAZ_ID int(12) UNSIGNED NOT NULL,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRICE double DEFAULT NULL,
  ITEM_PRICE double DEFAULT NULL,
  ITEM_CURRENCY varchar(10) DEFAULT NULL,
  PURCHASE_PRICE double DEFAULT NULL,
  QUANTITY double DEFAULT NULL,
  COST double DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ITEM_ID),
  INDEX CURRENCY_ID (CURRENCY_ID),
  INDEX ITEM_ID (ITEM_ID),
  INDEX ZAKAZ_ID (ZAKAZ_ID),
  CONSTRAINT ZAKAZ_ITEM_ibfk_1 FOREIGN KEY (ZAKAZ_ID)
  REFERENCES ZAKAZ (ZAKAZ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ZAKAZ_ITEM_ibfk_2 FOREIGN KEY (ITEM_ID)
  REFERENCES ITEM (ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ZAKAZ_ITEM_ibfk_3 FOREIGN KEY (CURRENCY_ID)
  REFERENCES CURRENCY (CURRENCY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 8851
AVG_ROW_LENGTH = 100
CHARACTER SET utf8
COLLATE utf8_general_ci;
