--
-- Описание для таблицы ZAKAZ_OLD
--
CREATE TABLE ZAKAZ_OLD (
  ZAKAZ_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID int(12) UNSIGNED DEFAULT NULL,
  CMF_USER_ID int(12) UNSIGNED NOT NULL,
  SUPPLIER_ID int(12) UNSIGNED NOT NULL,
  PAYMENT int(12) UNSIGNED NOT NULL,
  DATA datetime DEFAULT NULL,
  DELIVERYDATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  SURNAME varchar(255) NOT NULL DEFAULT '',
  EMAIL varchar(255) DEFAULT NULL,
  TELMOB varchar(255) DEFAULT NULL,
  ADDRESS varchar(255) DEFAULT NULL,
  INFO text DEFAULT NULL,
  STATUS int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 5951
AVG_ROW_LENGTH = 301
CHARACTER SET utf8
COLLATE utf8_general_ci;
