mkdir "../../images/social/"
mkdir "../../images/bn/"
mkdir "../../images/article/"
mkdir "../../images/news/"
mkdir "../../images/it_link/"
mkdir "../../images/it_link/"
mkdir "../../images/attr/"
mkdir "../../images/attr/"
mkdir "../../images/cat/"
mkdir "../../images/disc/"
mkdir "../../images/it/"
mkdir "../../images/br/"
mkdir "../../images/pg/"
mkdir "../../images/adm/scr/"
mkdir "../../images/textes/"
mkdir "../../images/usr_disc/"

