-- Скрипт сгенерирован Devart dbForge Studio for MySQL, Версия 6.0.189.1
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/mysql/studio
-- Дата скрипта: 03.06.2013 17:40:57
-- Версия сервера: 5.5.14
-- Пожалуйста, сохраните резервную копию Вашей схемы перед запуском этого скрипта 

CREATE DATABASE IF NOT EXISTS dominion_db COLLATE utf8_general_ci;
USE dominion_db;

-- ..\PreDeployment.sql
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;



-- ..\ALIASES.Table.sql
--
-- Описание для таблицы ALIASES
--
CREATE TABLE ALIASES (
  ALIASES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ALIASES_ID),
  INDEX idx_ALIASES_1 (ITEM_ID),
  INDEX idx_ALIASES_2 (BRAND_ID, NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ALIGN.Table.sql
--
-- Описание для таблицы ALIGN
--
CREATE TABLE ALIGN (
  ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 23
AVG_ROW_LENGTH = 42
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ANNOUNCEMENTS.Table.sql
--
-- Описание для таблицы ANNOUNCEMENTS
--
CREATE TABLE ANNOUNCEMENTS (
  ANN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  FIO varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  PRICE varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  PHONE varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  POSTED_AT datetime DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ANN_ID),
  INDEX idx_ANNOUNCEMENTS_1 (BRAND_ID, ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ANOTHER_PAGES.Table.sql
--
-- Описание для таблицы ANOTHER_PAGES
--
CREATE TABLE ANOTHER_PAGES (
  ANOTHER_PAGES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  REALCATNAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  TEMPLATE varchar(255) DEFAULT NULL,
  TITLE text DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  KEYWORDS text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  IS_NEW_WIN int(1) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDER_ int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ANOTHER_PAGES_ID),
  INDEX idx_ANOTHER_PAGES_1 (PARENT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 61
AVG_ROW_LENGTH = 253
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ARTICLE.Table.sql
--
-- Описание для таблицы ARTICLE
--
CREATE TABLE ARTICLE (
  ARTICLE_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ARTICLE_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE1 varchar(255) NOT NULL DEFAULT '',
  URL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ARTICLE_ID),
  INDEX idx_ARTICLE_1 (DATA),
  INDEX idx_ARTICLE_2 (ARTICLE_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 27
AVG_ROW_LENGTH = 864
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ARTICLE_GROUP.Table.sql
--
-- Описание для таблицы ARTICLE_GROUP
--
CREATE TABLE ARTICLE_GROUP (
  ARTICLE_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ARTICLE_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ATTR_CATALOG_LINK.Table.sql
--
-- Описание для таблицы ATTR_CATALOG_LINK
--
CREATE TABLE ATTR_CATALOG_LINK (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  IN_PODBOR int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID, ATTRIBUT_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 13
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ATTR_CATALOG_VIS.Table.sql
--
-- Описание для таблицы ATTR_CATALOG_VIS
--
CREATE TABLE ATTR_CATALOG_VIS (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CATALOGUE_ID, ATTRIBUT_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ATTRIBUT.Table.sql
--
-- Описание для таблицы ATTRIBUT
--
CREATE TABLE ATTRIBUT (
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  ID_FROM_VBD int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  TITLE text DEFAULT NULL,
  ICON_IMAGE varchar(50) DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  UNIT_ID int(12) UNSIGNED DEFAULT NULL,
  VIEW_ATTRIBUT_GROUP_ID int(12) UNSIGNED NOT NULL,
  ALTER_VALUE varchar(255) DEFAULT NULL,
  SHOW_ int(1) UNSIGNED DEFAULT NULL,
  SHOW_RIGHT int(1) UNSIGNED DEFAULT NULL,
  IS_LINK int(1) UNSIGNED DEFAULT NULL,
  IS_RANGEABLE int(1) UNSIGNED DEFAULT NULL,
  IS_RANGE_VIEW tinyint(1) UNSIGNED DEFAULT NULL,
  IS_CHOISE int(1) UNSIGNED DEFAULT NULL,
  NOT_CARD int(1) NOT NULL DEFAULT 0,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  MULTIPLE_ int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD)
)
ENGINE = MYISAM
AUTO_INCREMENT = 6280
AVG_ROW_LENGTH = 75
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ATTRIBUT_GROUP.Table.sql
--
-- Описание для таблицы ATTRIBUT_GROUP
--
CREATE TABLE ATTRIBUT_GROUP (
  ATTRIBUT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 202
AVG_ROW_LENGTH = 47
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ATTRIBUT_LIST.Table.sql
--
-- Описание для таблицы ATTRIBUT_LIST
--
CREATE TABLE ATTRIBUT_LIST (
  ATTRIBUT_LIST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  COMMENT_ text DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 23885
AVG_ROW_LENGTH = 33
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\BANN_SECTION.Table.sql
--
-- Описание для таблицы BANN_SECTION
--
CREATE TABLE BANN_SECTION (
  BANN_SECTION_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (BANN_SECTION_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 21
AVG_ROW_LENGTH = 44
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\BRAND.Table.sql
--
-- Описание для таблицы BRAND
--
CREATE TABLE BRAND (
  BRAND_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  IMAGE varchar(255) NOT NULL,
  TITLE varchar(255) DEFAULT NULL,
  SUBTITLE varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  ALT_NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IN_INDEX int(1) UNSIGNED NOT NULL,
  IN_ALL_PAGES int(1) UNSIGNED NOT NULL,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (BRAND_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD),
  INDEX idx_BRAND_1 (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 13867150
AVG_ROW_LENGTH = 53
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CALLBACK.Table.sql
--
-- Описание для таблицы CALLBACK
--
CREATE TABLE CALLBACK (
  CALLBACK_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PHONE varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CALLBACK_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 615
AVG_ROW_LENGTH = 819
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CAT_BRAND.Table.sql
--
-- Описание для таблицы CAT_BRAND
--
CREATE TABLE CAT_BRAND (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  BRAND_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID, BRAND_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 13
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CAT_HOME_TYPE.Table.sql
--
-- Описание для таблицы CAT_HOME_TYPE
--
CREATE TABLE CAT_HOME_TYPE (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  HOME_TYPE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CATALOGUE_ID, HOME_TYPE_ID),
  INDEX idx_CAT_HOME_TYPE_1 (HOME_TYPE_ID)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CAT_ITEM.Table.sql
--
-- Описание для таблицы CAT_ITEM
--
CREATE TABLE CAT_ITEM (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  ITEM_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CATALOGUE_ID, ITEM_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CATALOGUE.Table.sql
--
-- Описание для таблицы CATALOGUE
--
CREATE TABLE CATALOGUE (
  CATALOGUE_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(12) UNSIGNED NOT NULL,
  PARENT_ID int(12) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  NAME_ALTER varchar(255) DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  REALCATNAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  SUB_ITEM_TITLE varchar(255) NOT NULL DEFAULT '',
  SUB_TITLE varchar(255) NOT NULL DEFAULT '',
  DESC_META text DEFAULT NULL,
  KEYWORD_META text DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  SEO_LEFT text DEFAULT NULL,
  SEO_RIGHT text DEFAULT NULL,
  SEO_BOTTOM text DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  COUNT_ int(12) UNSIGNED DEFAULT NULL,
  IN_ADV int(1) UNSIGNED NOT NULL,
  IS_INDEX tinyint(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_ID),
  INDEX ID_FROM_VBD (ID_FROM_VBD),
  INDEX idx_CATALOGUE_1 (PARENT_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 281
AVG_ROW_LENGTH = 1086
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CATALOGUE_BRAND_VIEW.Table.sql
--
-- Описание для таблицы CATALOGUE_BRAND_VIEW
--
CREATE TABLE CATALOGUE_BRAND_VIEW (
  CATALOGUE_BRAND_VIEW_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_BRAND_VIEW_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 538
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\CATALOGUE_PRICE_EXPORT.Table.sql
--
-- Описание для таблицы CATALOGUE_PRICE_EXPORT
--
CREATE TABLE CATALOGUE_PRICE_EXPORT (
  CATALOGUE_PRICE_EXPORT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  PRICE_EXPORT_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_PRICE_EXPORT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 530
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\CATALOGUE_SECTION_ALIGN.Table.sql
--
-- Описание для таблицы CATALOGUE_SECTION_ALIGN
--
CREATE TABLE CATALOGUE_SECTION_ALIGN (
  CATALOGUE_SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CATALOGUE_SECTION_ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 151
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\CMF_BUG.Table.sql
--
-- Описание для таблицы CMF_BUG
--
CREATE TABLE CMF_BUG (
  CMF_BUG_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_USER_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_BUG_ID),
  INDEX idx_CMF_BUG_1 (DATA)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_GROUP.Table.sql
--
-- Описание для таблицы CMF_GROUP
--
CREATE TABLE CMF_GROUP (
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  PRIMARY KEY (CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 52
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_LANG.Table.sql
--
-- Описание для таблицы CMF_LANG
--
CREATE TABLE CMF_LANG (
  CMF_LANG_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYSTEM_NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_LANG_ID),
  UNIQUE INDEX idx_CMF_LANG_1 (SYSTEM_NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 28
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_PARAM.Table.sql
--
-- Описание для таблицы CMF_PARAM
--
CREATE TABLE CMF_PARAM (
  CMF_PARAM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SYSNAME varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  VALUE varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_PARAM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_SCRIPT.Table.sql
--
-- Описание для таблицы CMF_SCRIPT
--
CREATE TABLE CMF_SCRIPT (
  CMF_SCRIPT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  ARTICLE varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  BACKGROUND varchar(255) DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  REALSTATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_SCRIPT_ID),
  INDEX idx_CMF_SCRIPT_1 (PARENT_ID),
  INDEX idx_CMF_SCRIPT_2 (ARTICLE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 163
AVG_ROW_LENGTH = 85
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_SCRIPT_GROUP.Table.sql
--
-- Описание для таблицы CMF_SCRIPT_GROUP
--
CREATE TABLE CMF_SCRIPT_GROUP (
  CMF_SCRIPT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  R int(1) UNSIGNED DEFAULT NULL,
  W int(1) UNSIGNED DEFAULT NULL,
  D int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_SCRIPT_ID, CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 163
AVG_ROW_LENGTH = 21
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_SCRIPT_USER.Table.sql
--
-- Описание для таблицы CMF_SCRIPT_USER
--
CREATE TABLE CMF_SCRIPT_USER (
  CMF_SCRIPT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_USER_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  R int(1) UNSIGNED DEFAULT NULL,
  W int(1) UNSIGNED DEFAULT NULL,
  D int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_SCRIPT_ID, CMF_USER_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 111
AVG_ROW_LENGTH = 21
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_USER.Table.sql
--
-- Описание для таблицы CMF_USER
--
CREATE TABLE CMF_USER (
  CMF_USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  MD5_ varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  LOGIN varchar(255) DEFAULT NULL,
  PASS_ varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CMF_USER_ID),
  INDEX idx_CMF_USER_1 (MD5_),
  INDEX idx_CMF_USER_2 (LOGIN)
)
ENGINE = MYISAM
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 91
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_USER_GROUP.Table.sql
--
-- Описание для таблицы CMF_USER_GROUP
--
CREATE TABLE CMF_USER_GROUP (
  CMF_USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CMF_GROUP_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (CMF_USER_ID, CMF_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CMF_XMLS_ARTICLE.Table.sql
--
-- Описание для таблицы CMF_XMLS_ARTICLE
--
CREATE TABLE CMF_XMLS_ARTICLE (
  TYPE int(12) UNSIGNED NOT NULL DEFAULT 0,
  ARTICLE varchar(255) DEFAULT NULL,
  EDIT varchar(255) DEFAULT NULL,
  VIEW varchar(255) DEFAULT NULL,
  PRIMARY KEY (TYPE)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 58
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\CREDIT.Table.sql
--
-- Описание для таблицы CREDIT
--
CREATE TABLE CREDIT (
  CREDIT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  LONG_TEXT text NOT NULL,
  PRIMARY KEY (CREDIT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 2908
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\CURRENCY.Table.sql
--
-- Описание для таблицы CURRENCY
--
CREATE TABLE CURRENCY (
  CURRENCY_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SNAME varchar(255) DEFAULT NULL,
  SNAME_TYPE int(12) UNSIGNED DEFAULT NULL,
  SYSTEM_NAME varchar(255) DEFAULT NULL,
  PRICE double DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (CURRENCY_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\DELIVERY.Table.sql
--
-- Описание для таблицы DELIVERY
--
CREATE TABLE DELIVERY (
  DELIVERY_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD varchar(5) NOT NULL DEFAULT '0',
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  LONG_TEXT text NOT NULL,
  PRIMARY KEY (DELIVERY_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 1468
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\DICTS.Table.sql
--
-- Описание для таблицы DICTS
--
CREATE TABLE DICTS (
  DICTS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  DICTS_GROUP_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (DICTS_ID),
  INDEX idx_DICTS_1 (DICTS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\DICTS_GROUP.Table.sql
--
-- Описание для таблицы DICTS_GROUP
--
CREATE TABLE DICTS_GROUP (
  DICTS_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (DICTS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\DISCOUNTS.Table.sql
--
-- Описание для таблицы DISCOUNTS
--
CREATE TABLE DISCOUNTS (
  DISCOUNT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  IMAGE1 varchar(255) NOT NULL DEFAULT '',
  ORDERING tinyint(4) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (DISCOUNT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 13
AVG_ROW_LENGTH = 64
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\GOODS_GROUP.Table.sql
--
-- Описание для таблицы GOODS_GROUP
--
CREATE TABLE GOODS_GROUP (
  GOODS_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  IMPORT_IDENT varchar(255) DEFAULT NULL,
  IMPORT_IDENT_XML varchar(100) DEFAULT NULL,
  IN_FRONT int(1) UNSIGNED DEFAULT NULL,
  IN_CATALOG int(1) UNSIGNED NOT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (GOODS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 56
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\GOODS_GROUP_ITEM_LINK.Table.sql
--
-- Описание для таблицы GOODS_GROUP_ITEM_LINK
--
CREATE TABLE GOODS_GROUP_ITEM_LINK (
  GOODS_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  PARENT_ID int(12) UNSIGNED DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  BASE_IMAGE varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  INDEX idx_GOODS_GROUP_ITEM_LINK_1 (GOODS_GROUP_ID),
  INDEX idx_GOODS_GROUP_ITEM_LINK_2 (ITEM_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM_DEL.Table.sql
--
-- Описание для таблицы ITEM_DEL
--
CREATE TABLE ITEM_DEL (
  ITEM_REAL int(11) NOT NULL DEFAULT 0,
  ARTICLE_REAL varchar(255) DEFAULT NULL,
  ITEM_DELETE int(11) DEFAULT NULL,
  PRIMARY KEY (ITEM_REAL),
  UNIQUE INDEX ARTICLE_REAL (ARTICLE_REAL)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 268
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM_ITEM.Table.sql
--
-- Описание для таблицы ITEM_ITEM
--
CREATE TABLE ITEM_ITEM (
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  ITEM_ITEM_ID int(12) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  INDEX ITEM_ID (ITEM_ID, ITEM_ITEM_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 17
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\ITEM_MEDIA.Table.sql
--
-- Описание для таблицы ITEM_MEDIA
--
CREATE TABLE ITEM_MEDIA (
  ITEM_MEDIA_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  MEDIA_FILE varchar(50) DEFAULT NULL,
  MEDIA_CODE text DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ITEM_MEDIA_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 150
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\ITEM_OLD.Table.sql
--
-- Описание для таблицы ITEM_OLD
--
CREATE TABLE ITEM_OLD (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED DEFAULT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  DISCOUNT_ID int(12) UNSIGNED DEFAULT NULL,
  WARRANTY_ID int(12) UNSIGNED NOT NULL,
  DELIVERY_ID int(12) UNSIGNED NOT NULL,
  CREDIT_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  ARTICLE varchar(255) DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRICE double DEFAULT NULL,
  PRICE1 double DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  PURCHASE_PRICE double NOT NULL,
  IMAGE2 varchar(50) DEFAULT NULL,
  IMAGE3 varchar(50) DEFAULT NULL,
  NEED_RESIZE int(1) UNSIGNED NOT NULL,
  BASE_IMAGE varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  SEO_BOTTOM text DEFAULT NULL,
  YANDEX_XML int(1) UNSIGNED DEFAULT NULL,
  TITLE varchar(255) NOT NULL,
  DESC_META text NOT NULL,
  KEYWORD_META text NOT NULL,
  DATE_INSERT date DEFAULT NULL,
  IS_ACTION tinyint(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID),
  INDEX idx_ITEM_1 (CATALOGUE_ID),
  INDEX idx_ITEM_2 (BRAND_ID),
  INDEX idx_ITEM_3 (ARTICLE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16505
AVG_ROW_LENGTH = 150
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM_PHOTO.Table.sql
--
-- Описание для таблицы ITEM_PHOTO
--
CREATE TABLE ITEM_PHOTO (
  ITEM_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  IMAGE2 varchar(50) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 10269
AVG_ROW_LENGTH = 78
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\ITEM_REQUEST.Table.sql
--
-- Описание для таблицы ITEM_REQUEST
--
CREATE TABLE ITEM_REQUEST (
  ITEM_REQUEST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_REQUEST_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 49
AVG_ROW_LENGTH = 341
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM_TEMP.Table.sql
--
-- Описание для таблицы ITEM_TEMP
--
CREATE TABLE ITEM_TEMP (
  ITEM_TEMP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE text DEFAULT NULL,
  PRIMARY KEY (ITEM_TEMP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 488336
AVG_ROW_LENGTH = 45
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM0.Table.sql
--
-- Описание для таблицы ITEM0
--
CREATE TABLE ITEM0 (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEM0_1 (ATTRIBUT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 44402
AVG_ROW_LENGTH = 13
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM1.Table.sql
--
-- Описание для таблицы ITEM1
--
CREATE TABLE ITEM1 (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE double DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEM1_1 (ATTRIBUT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM2.Table.sql
--
-- Описание для таблицы ITEM2
--
CREATE TABLE ITEM2 (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEM2_1 (ATTRIBUT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 44402
AVG_ROW_LENGTH = 41
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM7.Table.sql
--
-- Описание для таблицы ITEM7
--
CREATE TABLE ITEM7 (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  VALUE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEM7_1 (ATTRIBUT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEMR.Table.sql
--
-- Описание для таблицы ITEMR
--
CREATE TABLE ITEMR (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  RANGE_LIST_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID, ATTRIBUT_ID),
  INDEX idx_ITEMR_1 (ATTRIBUT_ID, RANGE_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\MANAGERS.Table.sql
--
-- Описание для таблицы MANAGERS
--
CREATE TABLE MANAGERS (
  MANAGER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  EMAIL_STATUS int(1) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (MANAGER_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 56
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\MESSAGES.Table.sql
--
-- Описание для таблицы MESSAGES
--
CREATE TABLE MESSAGES (
  MESSAGES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  TEXT text DEFAULT NULL,
  ACTION int(12) UNSIGNED DEFAULT NULL,
  STATE_ int(12) UNSIGNED DEFAULT NULL,
  ADMIN int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (MESSAGES_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 1285
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\MESSAGES_SHOPUSER.Table.sql
--
-- Описание для таблицы MESSAGES_SHOPUSER
--
CREATE TABLE MESSAGES_SHOPUSER (
  MESSAGES_ID int(12) UNSIGNED NOT NULL,
  USER_ID int(12) UNSIGNED NOT NULL,
  WAS_SEND tinyint(3) UNSIGNED NOT NULL,
  INDEX MESSAGES_ID (MESSAGES_ID, USER_ID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 10
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\NEWS.Table.sql
--
-- Описание для таблицы NEWS
--
CREATE TABLE NEWS (
  NEWS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NEWS_GROUP_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE1 varchar(255) NOT NULL DEFAULT '',
  URL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (NEWS_ID),
  INDEX idx_NEWS_1 (DATA),
  INDEX idx_NEWS_2 (NEWS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 190
AVG_ROW_LENGTH = 364
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\NEWS_GROUP.Table.sql
--
-- Описание для таблицы NEWS_GROUP
--
CREATE TABLE NEWS_GROUP (
  NEWS_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (NEWS_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 29
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\OLD_SEF_URL.Table.sql
--
-- Описание для таблицы OLD_SEF_URL
--
CREATE TABLE OLD_SEF_URL (
  OLD_SEF_URL_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SEF_SITE_URL_ID int(12) UNSIGNED DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  PRIMARY KEY (OLD_SEF_URL_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1061
AVG_ROW_LENGTH = 52
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\PAYMENT.Table.sql
--
-- Описание для таблицы PAYMENT
--
CREATE TABLE PAYMENT (
  PAYMENT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (PAYMENT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 48
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\PRICE_EXPORT.Table.sql
--
-- Описание для таблицы PRICE_EXPORT
--
CREATE TABLE PRICE_EXPORT (
  PRICE_EXPORT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  INDENT varchar(255) DEFAULT NULL,
  PRIMARY KEY (PRICE_EXPORT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 27
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\RANGE_LIST.Table.sql
--
-- Описание для таблицы RANGE_LIST
--
CREATE TABLE RANGE_LIST (
  RANGE_LIST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUT_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  MIN double DEFAULT NULL,
  MAX double DEFAULT NULL,
  COMMENT_ text DEFAULT NULL,
  ICON varchar(50) DEFAULT NULL,
  ICON2 varchar(50) DEFAULT NULL,
  SHOW_ int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ATTRIBUT_ID, RANGE_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 46
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\REDIRECTOR.Table.sql
--
-- Описание для таблицы REDIRECTOR
--
CREATE TABLE REDIRECTOR (
  REDIRECTOR_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  URL_FROM varchar(255) DEFAULT NULL,
  URL_TO varchar(255) DEFAULT NULL,
  PRIMARY KEY (REDIRECTOR_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 72
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\RESPONSES.Table.sql
--
-- Описание для таблицы RESPONSES
--
CREATE TABLE RESPONSES (
  RESPONSES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ITEM_ID int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  HIDE int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (RESPONSES_ID),
  INDEX idx_RESPONSES_1 (ITEM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 809
AVG_ROW_LENGTH = 367
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SEARCH_CASH.Table.sql
--
-- Описание для таблицы SEARCH_CASH
--
CREATE TABLE SEARCH_CASH (
  SEARCH_CASH varchar(32) NOT NULL,
  SEARCH_NAME varchar(255) NOT NULL,
  ITEMS mediumtext NOT NULL,
  ITEMS_COUNT int(12) NOT NULL,
  PRIMARY KEY (SEARCH_CASH)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SEARCH_CASH_ITEM.Table.sql
--
-- Описание для таблицы SEARCH_CASH_ITEM
--
CREATE TABLE SEARCH_CASH_ITEM (
  ITEM_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  SEARCH_CASH text NOT NULL,
  PRIMARY KEY (ITEM_ID),
  INDEX BRAND_ID (BRAND_ID),
  INDEX CATALOGUE_ID (CATALOGUE_ID),
  FULLTEXT INDEX SEARCH_CASH (SEARCH_CASH)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 80
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SECTION_ALIGN.Table.sql
--
-- Описание для таблицы SECTION_ALIGN
--
CREATE TABLE SECTION_ALIGN (
  BANN_SECTION_ID int(12) UNSIGNED NOT NULL DEFAULT 0,
  SECTION_ALIGN_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ALIGN_ID int(12) UNSIGNED DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  ALT varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  BANNER_CODE text DEFAULT NULL,
  TYPE int(12) UNSIGNED DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  NEWWIN int(1) UNSIGNED DEFAULT NULL,
  IS_ADV int(1) UNSIGNED NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED NOT NULL,
  PRIMARY KEY (BANN_SECTION_ID, SECTION_ALIGN_ID),
  INDEX idx_SECTION_ALIGN_1 (ALIGN_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 276
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SEF_SITE_URL.Table.sql
--
-- Описание для таблицы SEF_SITE_URL
--
CREATE TABLE SEF_SITE_URL (
  SEF_SITE_URL_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SEF_URL varchar(255) DEFAULT NULL,
  SITE_URL varchar(255) DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  PRIMARY KEY (SEF_SITE_URL_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2030
AVG_ROW_LENGTH = 93
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SEQUENCES.Table.sql
--
-- Описание для таблицы SEQUENCES
--
CREATE TABLE SEQUENCES (
  SEQUENCES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SEQUENCES_ID),
  UNIQUE INDEX idx_SEQUENCES_1 (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 77
AVG_ROW_LENGTH = 24
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SETINGS.Table.sql
--
-- Описание для таблицы SETINGS
--
CREATE TABLE SETINGS (
  SETINGS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYSTEM_NAME varchar(255) DEFAULT NULL,
  VALUE text DEFAULT NULL,
  PRIMARY KEY (SETINGS_ID),
  UNIQUE INDEX idx_SETINGS_1 (SYSTEM_NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 48
AVG_ROW_LENGTH = 138
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SHOPUSER.Table.sql
--
-- Описание для таблицы SHOPUSER
--
CREATE TABLE SHOPUSER (
  USER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SHOPUSER_DISCOUNTS_ID int(12) UNSIGNED NOT NULL,
  IS_NEW int(1) UNSIGNED DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  SURNAME varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  BONUS text NOT NULL,
  REGDATA datetime DEFAULT NULL,
  PRIVATEINFO text DEFAULT NULL,
  TELMOB varchar(255) DEFAULT NULL,
  TELMOBT1 varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  UNIQUE INDEX UK_SHOPUSER_EMAIL (EMAIL)
)
ENGINE = MYISAM
AUTO_INCREMENT = 945
AVG_ROW_LENGTH = 185
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SHOPUSER_DISCOUNTS.Table.sql
--
-- Описание для таблицы SHOPUSER_DISCOUNTS
--
CREATE TABLE SHOPUSER_DISCOUNTS (
  SHOPUSER_DISCOUNTS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  CLASS_NAME varchar(255) DEFAULT NULL,
  MIN double NOT NULL,
  MAX double NOT NULL,
  IMAGE1 varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  IMAGE2 varchar(255) DEFAULT NULL,
  COLOR varchar(20) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SHOPUSER_DISCOUNTS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 109
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SHOPUSER_DISCOUNTS_RANGE_LIST.Table.sql
--
-- Описание для таблицы SHOPUSER_DISCOUNTS_RANGE_LIST
--
CREATE TABLE SHOPUSER_DISCOUNTS_RANGE_LIST (
  SHOPUSER_DISCOUNTS_RANGE_LIST_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SHOPUSER_DISCOUNTS_ID int(12) UNSIGNED NOT NULL,
  MIN double DEFAULT NULL,
  MAX double DEFAULT NULL,
  DISCOUNT_SUMM varchar(255) DEFAULT NULL,
  PRIMARY KEY (SHOPUSER_DISCOUNTS_RANGE_LIST_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 28
AVG_ROW_LENGTH = 33
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SHOPUSER_SUBSCRIBE_CLIENT_GROUP.Table.sql
--
-- Описание для таблицы SHOPUSER_SUBSCRIBE_CLIENT_GROUP
--
CREATE TABLE SHOPUSER_SUBSCRIBE_CLIENT_GROUP (
  SHOPUSER_SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED NOT NULL,
  USER_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SHOPUSER_SUBSCRIBE_CLIENT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 13
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SITE_PARAM.Table.sql
--
-- Описание для таблицы SITE_PARAM
--
CREATE TABLE SITE_PARAM (
  PARAM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SYSNAME varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  VALUE varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (PARAM_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\SOCIALS.Table.sql
--
-- Описание для таблицы SOCIALS
--
CREATE TABLE SOCIALS (
  SOCIALS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME text DEFAULT NULL,
  INDENT varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SOCIALS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 109
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SUBSCRIBE_CLIENT_GROUP.Table.sql
--
-- Описание для таблицы SUBSCRIBE_CLIENT_GROUP
--
CREATE TABLE SUBSCRIBE_CLIENT_GROUP (
  SUBSCRIBE_CLIENT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (SUBSCRIBE_CLIENT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 24
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\SUPPLIER.Table.sql
--
-- Описание для таблицы SUPPLIER
--
CREATE TABLE SUPPLIER (
  SUPPLIER_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (SUPPLIER_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 24
AVG_ROW_LENGTH = 20
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\TEXTES.Table.sql
--
-- Описание для таблицы TEXTES
--
CREATE TABLE TEXTES (
  TEXTES_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  SYS_NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  IMAGE varchar(50) DEFAULT NULL,
  PRIMARY KEY (TEXTES_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\TRANSLIT_RULE.Table.sql
--
-- Описание для таблицы TRANSLIT_RULE
--
CREATE TABLE TRANSLIT_RULE (
  TRANSLIT_RULE_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  SRC varchar(255) DEFAULT NULL,
  TRANSLIT varchar(255) DEFAULT NULL,
  PRIMARY KEY (TRANSLIT_RULE_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 156
AVG_ROW_LENGTH = 26
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\UNIT.Table.sql
--
-- Описание для таблицы UNIT
--
CREATE TABLE UNIT (
  UNIT_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (UNIT_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 92
AVG_ROW_LENGTH = 21
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\VIEW_ATTRIBUT_GROUP.Table.sql
--
-- Описание для таблицы VIEW_ATTRIBUT_GROUP
--
CREATE TABLE VIEW_ATTRIBUT_GROUP (
  VIEW_ATTRIBUT_GROUP_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (VIEW_ATTRIBUT_GROUP_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 299
AVG_ROW_LENGTH = 29
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\WARRANTY.Table.sql
--
-- Описание для таблицы WARRANTY
--
CREATE TABLE WARRANTY (
  WARRANTY_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_FROM_VBD int(1) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION text DEFAULT NULL,
  LONG_TEXT text NOT NULL,
  PRIMARY KEY (WARRANTY_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 1650
CHARACTER SET cp1251
COLLATE cp1251_ukrainian_ci;



-- ..\XMLS.Table.sql
--
-- Описание для таблицы XMLS
--
CREATE TABLE XMLS (
  XMLS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  TYPE int(12) UNSIGNED NOT NULL DEFAULT 0,
  XML text DEFAULT NULL,
  PRIMARY KEY (XMLS_ID, TYPE)
)
ENGINE = MYISAM
AUTO_INCREMENT = 20294
AVG_ROW_LENGTH = 3224
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZ.Table.sql
--
-- Описание для таблицы ZAKAZ
--
CREATE TABLE ZAKAZ (
  ZAKAZ_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID int(12) UNSIGNED DEFAULT NULL,
  CMF_USER_ID int(12) UNSIGNED NOT NULL,
  SUPPLIER_ID int(12) UNSIGNED NOT NULL,
  PAYMENT int(12) UNSIGNED DEFAULT NULL,
  DATA datetime DEFAULT NULL,
  DELIVERYDATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  SURNAME varchar(255) NOT NULL DEFAULT '',
  EMAIL varchar(255) DEFAULT NULL,
  TELMOB varchar(255) DEFAULT NULL,
  ADDRESS varchar(255) DEFAULT NULL,
  INFO text DEFAULT NULL,
  STATUS int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 8493
AVG_ROW_LENGTH = 227
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZ_ITEM_OLD.Table.sql
--
-- Описание для таблицы ZAKAZ_ITEM_OLD
--
CREATE TABLE ZAKAZ_ITEM_OLD (
  ZAKAZ_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ZAKAZ_ID int(12) UNSIGNED NOT NULL,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRICE double DEFAULT NULL,
  ITEM_PRICE double DEFAULT NULL,
  ITEM_CURRENCY varchar(10) DEFAULT NULL,
  PURCHASE_PRICE double DEFAULT NULL,
  QUANTITY double DEFAULT NULL,
  COST double DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ITEM_ID),
  INDEX CURRENCY_ID (CURRENCY_ID),
  INDEX ITEM_ID (ITEM_ID),
  INDEX ZAKAZ_ID (ZAKAZ_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 6073
AVG_ROW_LENGTH = 100
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZ_OLD.Table.sql
--
-- Описание для таблицы ZAKAZ_OLD
--
CREATE TABLE ZAKAZ_OLD (
  ZAKAZ_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID int(12) UNSIGNED DEFAULT NULL,
  CMF_USER_ID int(12) UNSIGNED NOT NULL,
  SUPPLIER_ID int(12) UNSIGNED NOT NULL,
  PAYMENT int(12) UNSIGNED NOT NULL,
  DATA datetime DEFAULT NULL,
  DELIVERYDATA datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  SURNAME varchar(255) NOT NULL DEFAULT '',
  EMAIL varchar(255) DEFAULT NULL,
  TELMOB varchar(255) DEFAULT NULL,
  ADDRESS varchar(255) DEFAULT NULL,
  INFO text DEFAULT NULL,
  STATUS int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 5951
AVG_ROW_LENGTH = 301
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZSTATUS.Table.sql
--
-- Описание для таблицы ZAKAZSTATUS
--
CREATE TABLE ZAKAZSTATUS (
  ZAKAZSTATUS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  COLOR varchar(20) NOT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZSTATUS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 37
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZSTATUS_OLD.Table.sql
--
-- Описание для таблицы ZAKAZSTATUS_OLD
--
CREATE TABLE ZAKAZSTATUS_OLD (
  ZAKAZSTATUS_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  COLOR varchar(20) NOT NULL,
  ORDERING int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZSTATUS_ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 37
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ITEM.Table.sql
--
-- Описание для таблицы ITEM
--
CREATE TABLE ITEM (
  ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  TYPENAME varchar(255) DEFAULT NULL,
  BRAND_ID int(12) UNSIGNED DEFAULT NULL,
  DISCOUNT_ID int(12) UNSIGNED DEFAULT NULL,
  WARRANTY_ID int(12) UNSIGNED NOT NULL,
  DELIVERY_ID int(12) UNSIGNED NOT NULL,
  CREDIT_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  CATNAME varchar(255) NOT NULL,
  ARTICLE varchar(255) NOT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRICE double DEFAULT NULL,
  PRICE1 double DEFAULT NULL,
  IMAGE1 varchar(50) DEFAULT NULL,
  PURCHASE_PRICE double NOT NULL,
  IMAGE2 varchar(50) DEFAULT NULL,
  IMAGE3 varchar(50) DEFAULT NULL,
  NEED_RESIZE int(1) UNSIGNED NOT NULL,
  BASE_IMAGE varchar(255) NOT NULL,
  DESCRIPTION text DEFAULT NULL,
  SEO_BOTTOM text DEFAULT NULL,
  YANDEX_XML int(1) UNSIGNED DEFAULT NULL,
  TITLE varchar(255) NOT NULL,
  DESC_META text NOT NULL,
  CC_XML text DEFAULT NULL,
  KEYWORD_META text NOT NULL,
  DATE_INSERT date DEFAULT NULL,
  IS_ACTION tinyint(1) UNSIGNED NOT NULL,
  IS_CASHED tinyint(1) NOT NULL,
  STATUS int(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ITEM_ID),
  INDEX idx_ITEM_1 (CATALOGUE_ID),
  INDEX idx_ITEM_2 (BRAND_ID),
  UNIQUE INDEX idx_ITEM_3 (ARTICLE),
  CONSTRAINT FK_ITEM_CATALOGUE_CATALOGUE_ID FOREIGN KEY (CATALOGUE_ID)
  REFERENCES CATALOGUE (CATALOGUE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 44734
AVG_ROW_LENGTH = 2218
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\ZAKAZ_ITEM.Table.sql
--
-- Описание для таблицы ZAKAZ_ITEM
--
CREATE TABLE ZAKAZ_ITEM (
  ZAKAZ_ITEM_ID int(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  ZAKAZ_ID int(12) UNSIGNED NOT NULL,
  ITEM_ID int(12) UNSIGNED NOT NULL,
  CATALOGUE_ID int(12) UNSIGNED NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRICE double DEFAULT NULL,
  ITEM_PRICE double DEFAULT NULL,
  ITEM_CURRENCY varchar(10) DEFAULT NULL,
  PURCHASE_PRICE double DEFAULT NULL,
  QUANTITY double DEFAULT NULL,
  COST double DEFAULT NULL,
  CURRENCY_ID int(12) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ZAKAZ_ITEM_ID),
  INDEX CURRENCY_ID (CURRENCY_ID),
  INDEX ITEM_ID (ITEM_ID),
  INDEX ZAKAZ_ID (ZAKAZ_ID),
  CONSTRAINT ZAKAZ_ITEM_ibfk_1 FOREIGN KEY (ZAKAZ_ID)
  REFERENCES ZAKAZ (ZAKAZ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ZAKAZ_ITEM_ibfk_2 FOREIGN KEY (ITEM_ID)
  REFERENCES ITEM (ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ZAKAZ_ITEM_ibfk_3 FOREIGN KEY (CURRENCY_ID)
  REFERENCES CURRENCY (CURRENCY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 8851
AVG_ROW_LENGTH = 100
CHARACTER SET utf8
COLLATE utf8_general_ci;



-- ..\PostDeployment.sql
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

