UPDATE
  ITEM I
  SET I.DESCRIPTION = GetShortDescript(I.ITEM_ID)
  WHERE I.ITEM_ID = 42841;



UPDATE CATALOGUE C
JOIN ITEM I USING (CATALOGUE_ID)
SET I.DESCRIPTION = GetShortDescript(I.ITEM_ID)
WHERE (I.DESCRIPTION IS NULL OR I.DESCRIPTION = '')
AND I.STATUS = 1